apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/resrv-455422/notifications/production
          name: notifications
          env:
            - name: port
              value: '3000'
            - name: SMTP_USER
              value: oknott2000@gmail.com
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 412501934979-ccsk271lp8hnf7gfk2kjagbmb6icgbg7.apps.googleusercontent.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          ports:
            - containerPort: 3000
